/**
 * Build-time content manifest accessor.
 *
 * The Nitro server routes resolve the section list, counts, and page-by-slug
 * lookup from this statically-imported manifest — NOT from a runtime
 * `process.cwd()/content` filesystem read (which is unreliable once Nitro
 * bundles the server). The manifest is generated by `scripts/gen-content-manifest.ts`
 * (run by `scolta:build` / the `gen:content` prebuild step) and bundled into the
 * server build, mirroring how the Next demo loads content at build time.
 */

import { contentManifest } from "./content-manifest.js";
import type { GitMasteryPage, NavSection } from "./content.js";

export interface ContentManifest {
  count: number;
  sections: string[];
  nav: NavSection[];
  translatable: string[];
  pages: Record<string, GitMasteryPage>;
}

const data = contentManifest as unknown as ContentManifest;

export function manifestCount(): number {
  return data.count;
}

export function manifestSections(): string[] {
  return data.sections;
}

export function manifestNav(): NavSection[] {
  return data.nav;
}

export function manifestTranslatable(): string[] {
  return data.translatable;
}

/** Resolve a catch-all slug segment array to a page (or undefined). */
export function manifestPageBySlugSegments(segments: string[]): GitMasteryPage | undefined {
  return data.pages["/" + segments.join("/") + "/"];
}
