#!/usr/bin/env tsx
/**
 * Generate the build-time content manifest (`lib/content-manifest.json`).
 *
 * Reads the YAML corpus once at build time and emits the section list, counts,
 * sidebar nav, translatable slugs, and a url -> page map. The Nitro server
 * routes import this manifest instead of reading `content/` from the filesystem
 * at request time — so the count and doc pages resolve regardless of the server
 * process's working directory. Run by `npm run gen:content` (wired into
 * `scolta:build` and the prebuild/pretypecheck/pretest steps).
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import {
  loadAllPages,
  loadEnglishDocs,
  sectionNav,
  translatableSlugs,
  type GitMasteryPage,
} from "../lib/content.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const outFile = path.resolve(here, "..", "lib", "content-manifest.ts");

const docs = loadEnglishDocs();
const pages: Record<string, GitMasteryPage> = {};
for (const p of loadAllPages()) {
  pages[p.url] = p;
}

const manifest = {
  count: docs.length,
  sections: [...new Set(docs.map((d) => d.section))].filter(Boolean),
  nav: sectionNav(),
  translatable: translatableSlugs(),
  pages,
};

// Emit a plain TS module (not JSON) so the import needs no `type: "json"`
// attribute and bundles identically under tsc (NodeNext) and Nitro/rollup.
const banner =
  "// AUTO-GENERATED by scripts/gen-content-manifest.ts — do not edit.\n" +
  "// Regenerated by `npm run gen:content` (the gen:content / scolta:build step).\n";
fs.writeFileSync(outFile, `${banner}export const contentManifest = ${JSON.stringify(manifest)};\n`, "utf-8");
console.log(`[scolta] content manifest: ${docs.length} docs, ${Object.keys(pages).length} pages -> ${path.relative(process.cwd(), outFile)}`);
